site_name: pwd.dev
site_description: don't get lost in the sauce
site_url: https://mk.pwd.dev

copyright: Copyright &copy; 2024 pwd.dev

theme:
  name: material
  custom_dir: overrides
  logo: images/terminal_icon.png
  icon: 
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      # note: fontawesome/solid/note-sticky
      # abstract: fontawesome/solid/book
      # info: fontawesome/solid/circle-info
      # tip: fontawesome/solid/bullhorn
      # success: fontawesome/solid/check
      # question: fontawesome/solid/circle-question
      # warning: fontawesome/solid/triangle-exclamation
      # failure: fontawesome/solid/bomb
      # danger: fontawesome/solid/skull
      # bug: fontawesome/solid/robot
      # example: fontawesome/solid/flask
      # quote: fontawesome/solid/quote-left
  favicon: images/terminal_icon.png
  palette:
    - scheme: slate
      primary: green
      accent: deep orange
  features:
    - navigation.sections
    - navigation.expand
    - toc.follow
    - announce.dismiss
    - navigation.top


extra_css:
  - stylesheets/extra.css

nav:
  - home: index.md
  - pwd:
    - for your home: home.md
    - for your office: office.md
  - dot: 
    - blog: blog/index.md
  - dev: 
    - contact: contact.md
    - about: about.md

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fPTZarfn
    # - icon: simple/linkedin
    #   link: https://linkedin.com/in/jonathan

extra_javascript:
  - javascripts/feedback-form.js
  - javascripts/chat.js

plugins:

  - search
  
  - blog:
      archive: false
      categories : false
      blog_dir: blog

      categories_allowed:
        - Unset
        - Home
        - Office
      
      post_url_format: '{slug}'
  
  - tags:
      tags_file: blog/tags.md
  
  - rss:
      match_path: "posts/.*"
      pretty_print: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

  # - git-committers:
  #     enabled: true
  #     repository: j0nnnnn0/mk.pwd.dev
  #     branch: main
  #     token: !ENV GH_TOKEN
  # - git-revision-date-localized:
  #     type: date
  #     enabled: true
  #     fallback_to_build_date: false
  #     enable_creation_date: true
  
  - glightbox:
      manual: true
      skip_classes:
        - skip-lightbox
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: black
      shadow: true
